[build]
builder = "nixpacks"

[deploy]
startCommand = "python src/main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
cronSchedule = "0 */8 * * *"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
